### PR TITLE
easy generalizations of types in complex.v

### PR DESCRIPTION
**Pull request by affeldt-aist**

### CODE REVIEW

**Comment by CohenCyril** [comment]
Hi @affeldt-aist is there a reason why this is not a PR onto master?

**Comment by affeldt-aist** [comment]
None that I know. It was just to make it available where wip was happening, and since I understood that the final result could be ready soon, I did not even thought of it.

**Comment by CohenCyril** [comment]
I would prefer if this PR was on top of master.

**Comment by affeldt-aist** [comment]
PR merged with master

**Pull request closed without merging**
