### PR TITLE
test with mathcomp-1.8.0

### PR DESCRIPTION
**Pull request by affeldt-aist**
just so that compilation using mathcomp-1.8.0 goes through

### CODE REVIEW

**Comment by CohenCyril** [comment]
@affeldt-aist great thanks!
(Additionally, I am preparing a way bigger update)

**Comment by amahboubi** [comment]
HI @CohenCyril, it would be useful to tag a version of the library that compiles with mathcomp-1.8. For now, as far as I could test, nor master, nor 1.0.1 does.

**Comment by CohenCyril** [comment]
> HI @CohenCyril, it would be useful to tag a version of the library that compiles with mathcomp-1.8. For now, as far as I could test, nor master, nor 1.0.1 does.

I was in the process of a release during the last month, but it did not get through yet. I will make try to take shortcuts and release something tomorrow.

**Comment by amahboubi** [comment]
Awesome. This PR compiles out of the box, contrarily to what CI suggests (the problems seems to be only a docker issue).

**Comment by amahboubi** [comment]
So as far as I am concerned, releasing the code as is in this branch, would be ideal. Then a later one could introduce the improvements you have in mind.

**Comment by CohenCyril** [comment]
made a mistake reopening this branch as #18

**Pull request closed without merging**
