### PR TITLE
modulus of the inverse, easy consequence of normcM

### PR DESCRIPTION
**Pull request by ybertot**
modified:   theories/complex.v

### CODE REVIEW

**Comment by CohenCyril** [comment]
These are supposed to be internal lemmas, to instanciate `normedZmodType` structures. Why can't you use the ones from the theory: `normfV`?

**Comment by ybertot** [comment]
(fun (x : complex R) => `|x|) has type R[i] -> R[i] (modulo conversion), but I am interested in the function of type
complex R -> R, and I need the inversion property for this function.  Does it make sense?

**Comment by affeldt-aist** [comment]
Should we postpone this PR to the next release (1.1.4)?

**Comment by ybertot** [comment]
A use case for this lemma is visible in [Mohit Tekriwal's development](https://github.com/mohittkr/iterative_convergence.html).  This is apparently used to ease the intermixing of developments relying on Coquelicot.

**Comment by affeldt-aist** [comment]
> A use case for this lemma is visible in [Mohit Tekriwal's development](https://github.com/mohittkr/iterative_convergence.html). This is apparently used to ease the intermixing of developments relying on Coquelicot.

Maybe you mean this link https://github.com/mohittkr/iterative_convergence.

**Comment by ybertot** [comment]
Yes you are right.

**Comment by affeldt-aist** [comment]
Should we provide a section before `Section ComplexField` with the theory of `normc` and keep only the `normC` theory inside the `Section ComplexField`?

**Comment by affeldt-aist** [comment]
> Should we provide a section before `Section ComplexField` with the theory of `normc` and keep only the `normC` theory inside the `Section ComplexField`?

Something like https://github.com/math-comp/real-closed/pull/35/commits/4e9346fbf59fb9e1fce294472458f90fa05b516e ?

**Comment by affeldt-aist** [comment]
No opinion on this one? Should we postpone to the next release?

**Pull request merged**
