### PR TITLE
[CI] Add Coq 8.17 and MC 1.16

### PR DESCRIPTION
**Pull request by proux01**

### CODE REVIEW

**Comment by proux01** [comment]
@CohenCyril CI green, no hurry but this should enable you to release real-closed 1.1.4 (I can then do the OPAM package) compatible with Coq 8.17 and MC 1.16, which in turn would enable me to release CoqEAL.

**Comment by proux01** [comment]
@CohenCyril gentle ping, could you merge this and release a 1.1.4 so that I can prepare a relase of CoqEAL for COq 8.17?

**Comment by CohenCyril** [comment]
Thanks @proux01

**Comment by proux01** [comment]
@CohenCyril please let me know when you'll have done the release (last release 1.1.3 no longer compiles on Coq 8.17 as far as I can see).

**Comment by proux01** [comment]
Thanks, the release text reads "Compatible with 8.14 to 8.16 and with mathcomp 1.12.0 to 1.16.0" but according to the CI it seems to be rather "Compatible with 8.14 to 8.17 and with mathcomp 1.13.0 to 1.16.0"

**Comment by CohenCyril** [comment]
True ! Thanks

**Pull request merged**
